### ISSUE TITLE
Command mlkink /J returned non-zero exit status 1

### ISSUE THREAD

**Issue by ElijahRBerlin** [OpenGOAL-Unofficial-Mods/OpenGoal-ModLauncher-dev#42]
![Untitled](https://github.com/OpenGOAL-Unofficial-Mods/OpenGoal-ModLauncher-dev/assets/39922161/f9fb0b22-2420-4644-b411-6aad84fd966c)

I get this error every time I try to install a mod.  Afterwards, if I try to boot the mod, it launches successfully but then crashes after loading a save file after walking around a little bit.  The mod is deletes itself after that.

**Comment by dallmeyer** [comment]
I'm actually working on a fix for this today :)

**Comment by ElijahRBerlin** [comment]
Frick ya.  Thank you for all your hard work

**Comment by dallmeyer** [comment]
Should be fixed now I hope? If you're using the auto-updater from the website, it should automatically update the launcher for you

**Comment by ElijahRBerlin** [comment]
Thank you so much for your help.  Most mods seem to be installing correctly now.  The only one I'm having trouble with is the Jak Up mod.  Idk if you can do anything about that tho.  I'm super looking forward to Jak II!  The open-goal project has gotten my techy friends into Jak & Daxter
![Screenshot 2023-10-15 220121](https://github.com/OpenGOAL-Unofficial-Mods/OpenGoal-ModLauncher-dev/assets/39922161/eec6b013-e955-4906-b89b-87adafb51c0b)

**Comment by dallmeyer** [comment]
Check the middle of that screenshot, there's an error about gk.exe being flagged as a virus, and gets deleted before it can run. Unfortunately windows defender or other antivirus software likes to do this to opengoal sometimes :/

**Comment by ElijahRBerlin** [comment]
Weird... Jak Up ssems to be the only one it has a problem with for me.  At least the other mods are working.  Thanks again for your help!

**Comment by dallmeyer** [comment]
You might need to go into windows defender and look for "protection history", and allow/restore the program. You'd be looking for `gk.exe` (and maybe extractor.exe)

**Comment by ElijahRBerlin** [comment]
That worked... for a moment...  Now the Mod Launcher doesn't remember any of the mods I've installed after I close them.  And some of the mods crash the mod launcher when I try to install.  I don't expect you to help me troubleshoot all night tho, and I have work in the morning.  Again, I appreciate your help. I will try again in the morning

**Comment by dallmeyer** [comment]
Forgot to come back and update here, there was one more bug which I fixed in the past couple days, so maybe give it another shot now @ElijahRBerlin ?

**Comment by ElijahRBerlin** [comment]
Thanks for the update.  I don't seem to have any problems installing mods now.  I do still have a problem with the Jak Up mod freezing or crashing shortly after starting a new save game.  In the meantime, I was so excited for Jak 2 that I couldn't wait and installed the project to play it early.  I love what y'all are doing, and I'm so excited for the full release.

**Comment by ElijahRBerlin** [comment]
![image](https://github.com/OpenGOAL-Unofficial-Mods/OpenGoal-ModLauncher-dev/assets/39922161/d5cd9d9f-49c6-4044-8c81-5fa9b7d95a53)
Specifically I'm getting this error if it helps.

**Comment by dallmeyer** [comment]
Hm that sounds like it didn't extract/generate the custom levels properly (`UP0` it failed to find there is the geyser rock custom level). The Jak-Up mod is pretty big, are you sure there's enough space on your drive? If you have < 1GB that could be the issue. I assume you've already tried uninstalling and reinstalling it?

**Comment by ElijahRBerlin** [comment]
Yes, I've tried uninstalling and installing it.  I still have 46 gb left afterwards.  If it helps, I'm also getting this error when installing it:
![image](https://github.com/OpenGOAL-Unofficial-Mods/OpenGoal-ModLauncher-dev/assets/39922161/de502bef-8852-48fa-84bd-76aed3e20de2)

**Comment by dallmeyer** [comment]
Hmm I'm not exactly sure what to make of that, seems like the iso data is in some weird state... 

Can you try manually navigating to `AppData\Roaming\OpenGOAL-Mods` and delete the entire `up` folder? I would also navigate to `AppData\Roaming\OpenGOAL-Mods\_iso_data` and delete the whole `jak1` folder within that - after that it should prompt you for your ISO the next time you launch/install a mod. 

Hopefully this will get you out of whatever state is causing issues

**Comment by ElijahRBerlin** [comment]
That seems to have fixed the issue!  I was have a problem where the game would crash after starting a new jak up save and walking a few feet, and that would cause the game to freeze the next time i tried to load a save file again, but it seems to have fixed itself even after re-launching.  I'm hoping it's just a fluke.  Again, thank you so much for troubleshooting this with me.  I love this project and I'm super excited for Jak 2 and 3.

**Comment by dallmeyer** [comment]
Nice! I was running out of ideas to try, glad it's finally working. Enjoy 👍
